services:

  db:
    image: postgres:latest
    volumes:
      - ./db_data:/var/lib/postgresql/18/docker
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
